name: Docker Image CI

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/modbus-everything-bridge:latest, ${{ secrets.DOCKERHUB_USERNAME }}/modbus-everything-bridge:${{ env.NOW }}
